movie-web/providers

.gitignore
README.md
package-lock.json
package.json
run-source.ts
src/dev-cli.ts
tsconfig.json

@binaryoverload Said on Discord I didn't need an issue open for this one
There is currently no way, provided by the repo, to test sources during development. This is aimed at making a system which can support this
~~Marking this as a draft for now since it needs changes, and as a first time contribution here I'm unsure if I followed everything to the preferred style~~
No longer a draft, ready for review
Adds a `run-source.ts` script to test running specific sources. Script supports both providers and embed sources. The script also has 2 execution modes:
- CLI mode, for passing in arguments directly to the script
- Question mode, where the script asks you questions about which source you wish to test
~~There are 2 big issues keeping this as a draft PR~~
1. ~~Native `fetch` is not working …

Added source testing script

---

.eslintrc.js
README.md
package-lock.json
package.json
src/providers/all.ts
src/providers/embeds/mp4upload.ts
src/providers/embeds/streamsb.ts
src/providers/sources/gomovies/index.ts
src/providers/sources/gomovies/source.ts
src/providers/sources/kissasian/common.ts
src/providers/sources/kissasian/getEmbeds.ts
src/providers/sources/kissasian/getEpisodes.ts
src/providers/sources/kissasian/index.ts
src/providers/sources/kissasian/search.ts
src/providers/sources/remotestream.ts
src/providers/sources/remotestream/common.ts
src/providers/sources/remotestream/index.ts
src/providers/sources/superstream/LICENSE
src/providers/sources/superstream/common.ts
src/providers/sources/superstream/crypto.ts
src/providers/sources/superstream/getStreamQualities.ts
src/providers/sources/superstream/index.ts
src/providers/sources/superstream/sendRequest.ts

This pull request resolves [#435](https://github.com/movie-web/movie-web/issues/435)
providers need to be ported to the new provider repo:
embeds:

Port Providers

---

.docs/package-lock.json
package-lock.json
package.json

see title, also bumps a version for the release

Fix vuln in packages (and bump version)

---

src/__test__/utils/valid.test.ts
src/main/runner.ts

changes:
- Fixed bug found during v4 development
- Added some extra tests for valid stream checks. just to be safe
@binaryoverload could you be a lad an review this when you got the time?
right after merge, I'd like to do a minor release as well.

Fix "incomplete stream" error on flixhq & zoechip

---

package.json
src/providers/sources/showbox/index.ts

changes:
- Fix "incomplete stream" bug on embed based sources

Provider package v1.0.3

---

package.json
src/providers/sources/showbox/index.ts

Fix superstream

---

src/providers/embeds/upcloud.ts

allow numbers in variable names

---

.docs/package-lock.json
.docs/package.json
package.json
src/providers/captions.ts
src/providers/embeds/febBox.ts
src/providers/embeds/mixdrop.ts
src/providers/embeds/mp4upload.ts
src/providers/embeds/streamsb.ts
src/providers/embeds/upcloud.ts
src/providers/embeds/upstream.ts
src/providers/sources/gomovies/index.ts
src/providers/sources/remotestream.ts
src/providers/sources/superstream/getStreamQualities.ts
src/providers/sources/superstream/index.ts
src/providers/sources/superstream/subtitles.ts
src/providers/streams.ts

Version 1.1.0

---

package.json
src/providers/embeds/upcloud.ts
src/providers/sources/flixhq/index.ts
src/providers/sources/superstream/index.ts
src/providers/sources/superstream/subtitles.ts

changes:
- handle error when superstream media can be found, but no file id exists.
- remove old todo thats been completed
- fix caching issues with upcloud script fetching
- bump a minor version

error handling and fixing caching problems

---

package.json
src/providers/sources/superstream/getStreamQualities.ts
src/providers/sources/superstream/subtitles.ts
src/providers/streams.ts

changes:
- Fix caching issue with upcloud key extractor
- Fix superstream throwing error instead of notfounderror.

providers v1.1.3

---

src/providers/sources/superstream/common.ts
src/providers/sources/superstream/subtitles.ts

This pull request fixes Superstream captions.

Superstream captions fix

---

package.json
src/providers/sources/gomovies/index.ts
src/providers/sources/showbox/index.ts
src/providers/sources/zoechip/index.ts

changes:
- rerank providers
- disable showbox

Rerankings

---

src/providers/sources/flixhq/search.ts

fix flixhq show searching

---

.docs/content/2.Api/3.ProviderControlsrunEmbedScraper.md

Correct function name for runEmbedScraper

---

package.json
src/providers/embeds/febbox/qualities.ts
src/runners/runner.ts

changes:
- fix quality selecting for febbox
- bump version
- fix sorting of embeds in discoverEmbeds event

Fix febbox qualities

---

src/providers/sources/lookmovie/index.ts
src/providers/sources/lookmovie/type.ts
src/providers/sources/lookmovie/util.ts
src/providers/sources/lookmovie/video.ts

---
Added support for captions in the LookMovie scraper.

feat(lookmovie): add captions support

---

src/providers/embeds/febbox/hls.ts

Remove CORS Allowed flag for febbox hls

---

src/providers/embeds/febbox/subtitles.ts

Fix language showing up more than once

---

.github/CODEOWNERS
src/entrypoint/providers.ts
src/providers/embeds/febbox/hls.ts

changes:
- mark febbox hls as disabled
- make getBuiltinSources and getBuiltinEmbeds ignore disabled providers

remove febbox HLS, it doesnt work

---

src/providers/sources/remotestream.ts

Fix remotestream base

---

src/providers/captions.ts
src/providers/embeds/febbox/subtitles.ts
src/providers/sources/lookmovie/index.ts
src/providers/sources/lookmovie/video.ts

Fix LookMovie caption codes, create removeDuplicateLanguages util

---

src/fetchers/simpleProxy.ts
src/providers/sources/showbox/sendRequest.ts

changes:
- Fix showbox by setting user-agent (still not compatible with cloudflare though, ip banned)
- Add support for newest simple-proxy headers

Fix showbox + add support for new simple-proxy version

---

.docs/content/1.get-started/4.changelog.md
package.json
src/providers/embeds/febbox/mp4.ts

changes:
- disabled febbox subs
- bump version
- update docs with changelog

Disable febbox subs

---

.docs/content/1.get-started/4.changelog.md
package.json
src/providers/embeds/febbox/mp4.ts

V2.0.5 - disable febbox subs

---

src/entrypoint/utils/targets.ts
src/providers/embeds/upcloud.ts
src/providers/embeds/vidplay/common.ts
src/providers/embeds/vidplay/index.ts
src/providers/sources/remotestream.ts
src/providers/sources/showbox/index.ts

changes:
- set preferred and required headers correctly for most streams
- add CF_BLOCKED flag

Extension support for providers

---

.docs/content/1.get-started/4.changelog.md
package.json
src/providers/sources/lookmovie/index.ts

changes:
- lookmovie highest rank :tada:
- version bump

Version bump + lookmovie reorder

---

.docs/content/1.get-started/4.changelog.md
package-lock.json
package.json
src/providers/embeds/vidplay/common.ts

changes:
- fix vidplay decryption keys and domain

Providers v2.1.1

---

src/providers/embeds/dood.ts
src/providers/embeds/wootly.ts
src/providers/sources/goojara/getEmbeds.ts
src/providers/sources/goojara/index.ts
src/providers/sources/goojara/util.ts

This pull request resolves Fixes GooJara, as they changed how seasons were found.

Fix Goojara Scraping and Capitalization of Id

---

.docs/content/1.get-started/0.introduction.md
.docs/content/2.essentials/0.usage-on-x.md
.github/SECURITY.md
package.json

security.md needs another look at

More old domain mentions

---

src/providers/sources/showbox/sendRequest.ts
src/utils/params.ts

This pull request fixes scraping for showbox in the native app for https://github.com/movie-web/native-app/pull/9.
The changes have been tested with the native app and nodejs.

Fix showbox scraper for native app

---

.docs/content/2.essentials/0.usage-on-x.md

This pull request resolves movie-web/movie-web#890

docs: Add setup steps to React native

---

src/providers/embeds/dood.ts

This pull request resolves movie-web/movie-web#997

Check if dood returns a valid url

---

src/providers/all.ts
src/providers/sources/hdrezka/index.ts
src/providers/sources/hdrezka/types.ts
src/providers/sources/hdrezka/utils.ts
src/utils/quality.ts

This pull request resolves discord requests 😄 , in continuation of #55 
Extension only source, the streams itself are IP Locked
It uses the mobile app endpoints, and this endpoint does not block specific countries.
I would appreciate it if someone else tests this too, just to make sure 🙂

Add hdrezka

---

src/providers/sources/hdrezka/index.ts
src/providers/sources/hdrezka/types.ts

Before (fails due to video missing translator 238):
After:

rezka: check for translator

---

src/providers/sources/remotestream.ts

domain expired a while ago and there is no new one

Disable remotestream

---

src/providers/sources/vidsrcto/index.ts

vidsrcto: use tmdbId when imdbId is not provided

---

src/providers/embeds/febbox/qualities.ts

Fix febbox

---

package.json

I have no idea how this even works on movie-web. Breaks the native app 😂

Fixing package.json export

---

src/providers/embeds/filemoon/index.ts
src/providers/embeds/vidplay/index.ts
src/providers/sources/vidsrcto/index.ts

Add CORS restrictions to vidsrcto source and vidplay embed 

---

src/providers/embeds/vidsrc.ts
src/providers/sources/vidsrc/common.ts
src/providers/sources/vidsrc/index.ts

Fix vidsrc.me

---

src/providers/all.ts
src/providers/sources/soapertv/index.ts
src/providers/sources/soapertv/types.ts

Extension only source (IP_LOCKED)

Add soapertv source

---

src/providers/all.ts
src/providers/embeds/bflix.ts
src/providers/sources/nites.ts

add nites.is source and bflix embed

---

src/providers/all.ts
src/providers/sources/tugaflix/common.ts
src/providers/sources/tugaflix/index.ts

mostly embeds streamtape
and sometimes dood

add Tugaflix source
