movie-web/providers

package-lock.json, package.json, src/providers/sources/superstream/sendRequest.ts
This pull request resolves #8 
#8 was caused due to the `nanoid` module not supporting CommonJS. The usage for `nanoid` in this case was just to generate a random 32 character hex string, which can easily be done in several other ways without needing `nanoid`
https://github.com/browserify/randombytes is now used to generate the hex string. It uses `crypto.randomBytes` when on the server and `crypto/msCrypto.getRandomValues` in the browser
Tested on a couple movies using the new test script and it works just fine
=> fix superstream

package-lock.json, package.json, src/providers/all.ts, src/providers/embeds/mixdrop.ts, src/providers/embeds/upstream.ts, src/providers/sources/zoechip/common.ts, src/providers/sources/zoechip/index.ts, src/providers/sources/zoechip/scrape-movie.ts, src/providers/sources/zoechip/scrape-show.ts, src/providers/sources/zoechip/scrape.ts, src/providers/sources/zoechip/search.ts, src/providers/streams.ts
- Added https://zoechip.cc/ source provider, both movies and TV shows
- Added https://mixdrop.co/ and https://upstream.to/ embed providers
- Added an optional `headers` property to `StreamFile`. This is required for mixdrop streams
- ~~Mixdrop returns mp4 file streams, but the only way to pass these is by using `qualities`. Mixdrop does not provide stream quality information, so this just defaults to 1080. I would propose that something like an `unknown` option also be added for `qualities` for these cases~~
- Not related to this PR, but something I noticed while working on it. `SourcererOutput` only currently allows for multiple embeds to be returned, but not multiple streams. There are cases where this is insufficient. I have written multiple scrapers in the past which return more than …
=> Add ZoeChip source & mixdrop and upstream embeds

package.json, src/providers/captions.ts, src/providers/embeds/febBox.ts, src/providers/embeds/mixdrop.ts, src/providers/embeds/mp4upload.ts, src/providers/embeds/streamsb.ts, src/providers/embeds/upcloud.ts, src/providers/embeds/upstream.ts, src/providers/sources/gomovies/index.ts, src/providers/sources/remotestream.ts, src/providers/sources/superstream/getStreamQualities.ts, src/providers/sources/superstream/index.ts, src/providers/sources/superstream/subtitles.ts, src/providers/streams.ts
This pull request resolves https://github.com/movie-web/movie-web/issues/487
changes:
- add linked subtitles to streams
- linked subtitle labels are normalized to the iso639-1 standard. non-confirming subs are ignored
- fixed gomovies scraper, who suddenly decided to stop using json and start using form urlencoded
- added 1080p support to superstream, since it was easy to do. thanks @zisra 
- only superstream and upcloud have support for linked subtitles, since movie-web v3 does the same.
=> Linked captions

package-lock.json, src/providers/all.ts, src/providers/base.ts, src/providers/embeds/smashystream/dued.ts, src/providers/embeds/smashystream/video1.ts, src/providers/sources/lookmovie/index.ts, src/providers/sources/smashystream/index.ts, src/providers/sources/zoechip/common.ts, src/providers/sources/zoechip/scrape-movie.ts, src/providers/sources/zoechip/scrape-show.ts, src/providers/sources/zoechip/scrape.ts, src/utils/context.ts
Based on https://github.com/JorrinKievit/restreamer/tree/main/src/main/extractors/smashystream. 
Completely missed the comment made on the issue in my repo 😅 -> https://github.com/JorrinKievit/restreamer/issues/8
Could start slowly phasing out my extractor/scraper logic and replace it with the package in here once we have added more providers.
- Added SmashyStream scraper for Player F and D (Player S is the movie-web embed 😉 )
- created a universal MovieScrapeContext and ShowScrapeContext. Saw it discussed in an older PR but since i also needed this type I thought I might as well add it.
Not too sure about the ranking, so it might be a bit random 😄
=> Smashystream scraper

package-lock.json, src/runners/individualRunner.ts, src/runners/runner.ts
This pull request resolves movie-web/movie-web#720
Result:
VidSrc no longer shows an "Unknown option", now there is no extra embed select since there is only one option
=> Add disabled embed filter to scrapeInvidualSource and runAllProviders

src/providers/embeds/vidsrc.ts
- Fixes VidSrc failing to decode and retrieve the source URL.
=> VidSrc: Remove equal signs inside base64 encoded string

package-lock.json, src/providers/embeds/vidplay/common.ts
- Replaced the decryption keys for Vidplay.
- Also switched domain, since the current one is timing out.
- Massive thanks to @Ciarands!
=> replace vidplay decryption keys and domain

src/providers/embeds/vidsrc.ts
This PR fixes vidsrc.me hls url decoding by recursively removing bad data in the b64.
=> Fix vidsrc.me url decoding

src/providers/sources/vidsrcto/index.ts
- Example show that is not working: https://movie-web.app/media/tmdb-tv-332-los-simuladores/978/17106
- Tested the code for both movies and shows with and without subtitles
=> Fixed VidSrcTo crashing if no subtitles are found

src/providers/streams.ts
changes:
- add option to return a thumbnail track. But not providers that support it yet.
=> Add thumbnail track option to response

src/providers/embeds/closeload.ts
The scraper was selecting the wrong script on the HTML page. Note that this source still wont work on the site, because of movie-web/movie-web#905
=> Fix closeload scraper

package-lock.json, src/providers/sources/ridomovies/index.ts
This pull request resolves ridomovies not working for some shows and movies because of differences in slugs between search result and player page. We now only check for season and episode number
=> fix ridomovies not working for some shows and movies

src/providers/embeds/upcloud.ts
For some streams, the caption labels of the UpCloud/VidCloud embeds include a suffix of the language in its native tongue (e.g. Dutch - Nederlands). This made the language code lookup fail and therefor no captions were returned by the scraper. This PR fixes this by only taking the first part of the label.
=> Fix missing captions from UpCloud/VidCloud embeds

src/fetchers/body.ts, src/providers/sources/showbox/sendRequest.ts, src/utils/native.ts, src/utils/params.ts
This allows users to still use URLSearchParams like they are used to, but have it work in react-native. This way contributors do not have to know that they are required to use a different function for creating URLSearchParams. 
react-native partially implements URLSearchParams (constructor and .append()), but does not support a class instance of URLSearchParams to be passed into the native fetch call. If we stringify the class, we achieve the desired result in react-native.
=> Fix URLSearchParams usage for react-native

src/providers/embeds/filemoon/index.ts, src/providers/embeds/vidplay/index.ts, src/providers/sources/vidsrcto/index.ts
This pull request fixes embedUrl matching for Vidplay and Filemoon sources
=> Fix embedUrl matching for Vidplay and Filemoon sources

src/utils/compare.ts
This pull request resolves #227
- Updated the normalizeTitle function to cover an edge case where the title contains the "The Movie"
=> Updated compare function to check a edge case

src/providers/sources/hdrezka/utils.ts
This pull request resolves the issue where the URL is logged in the console (for the discord bot)
=> Remove url logging

src/providers/sources/flixhq/index.ts, src/providers/sources/gomovies/index.ts, src/providers/sources/goojara/index.ts, src/providers/sources/nepu/index.ts, src/providers/sources/smashystream/index.ts, src/providers/sources/zoechip/index.ts
This pull request partially resolves [#1026](https://github.com/movie-web/movie-web/issues/1026)
Note -
I purposefully haven't disabled RidoMovies as the scraper seemingly still works, although the url does block you, It maybe works in some cases, I have no idea, if anyone wants to follow up with me on that, that'd be great.
If necessary we can disable RidoMovies, although imo we might as well just keep it as is, it seems like it could fix itself.
=> Disable sources that no longer work

src/providers/embeds/febbox/qualities.ts
Febbox now requires the queries removed by removeBadUrlParams.
=> febbox-mp4: remove removeBadUrlParams

src/runners/individualRunner.ts, src/runners/runner.ts, src/utils/valid.ts
We have encountered issues in our frontend because the providers library returns url's that are not valid. For example they return a 403 because of missing parameters in the URL. If a stream is not valid, it should not be returned by the providers library. With this implementation we validate if the URL is valid by sending a HEAD request before actually returning it. Now we also do not have to do this individually for each provider, since it is checked after the scrape.
Will do a bit more testing, but seems to work well
=> Validate if a stream is actually playable

src/utils/valid.ts
Lets try and fix it again shall we. Showbox does not accept HEAD requests on their mp4 files. It also CORS blocks it because of the Origin header that is passed in for regular requests, returning a "default_origin.com". So it needs to be proxied. We now request the first byte of the video file to see it resolve (see screenshot)
=> Fix showbox

src/providers/sources/ridomovies/index.ts
This pull request fixes ridomovies returning wrong media. Now it doesn't take the first result, it checks all the results for the title and releaseYear.
=> fix ridomovies search

src/providers/all.ts, src/providers/embeds/filemoon/index.ts, src/providers/embeds/filemoon/mp4.ts, src/providers/sources/vidsrcto/index.ts
This pull request adds support for Filemoon MP4 streams. All credit goes to Joost <@153779031295131648> on discord for showing me how to fetch the MP4 streams. 
Edit: @Ciarands <@1162435371683029122> found the exploit that makes this possible. Big thanks to him!
=> Add support for Filemoon MP4 streams
